In [1]:
import numpy as np

In [5]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

no difference

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
list = [ '1' , '2' , '3' , '4' , '5' ]

In [7]:
np.array(list)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
arr=np.array(list)

In [9]:
arr

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.

array_list = np.array(object = list_, dtype = int)


In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [6]:
arr=np.array(num_list)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.size

6

In [12]:
arr.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
data=np.random.randint(0,1,(3,3))

In [19]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
data.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
data1=np.diag([1,1,1,1,1,])

In [25]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])